plugin:
    type: interface
    description:
        de: 'Helios Modbus TCP KWL Plugin'
        en: 'Helios Modbus TCP KWL Plugin'
    maintainer: 'Stefan'
    tester: '-'
    keywords: 'helios modbus ventilation'
    documentation: 
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/
    version: 0.0.1                 # Plugin version
    sh_minversion: 1.1             # minimum shNG version to use this plugin
    multi_instance:  False         # plugin supports multi instance
    classname: 'HeliosTCP'            # class containing the plugin
# parameters:                        # Definition of parameters to be configured in etc/plugin.yaml
#    ip:
#        type: str
#        default: '127.0.0.1'
#        description:
#            de: 'IP für die Kommunikation'
#            en: 'IP for communication'
#    cycle: 'Polling interval in seconds'
#        type: num
#        default: 300
#        description:
#            de: 'Abfrage-Intervall'
#            en: 'Polling interval'
# item_attributes:
